export enum LocalStorageItemType {
  TEAMS = 'TEAMS',
  AREAS = 'AREAS',
  COPILOT_CONVERSATIONS = 'COPILOT_CONVERSATIONS',
  COPILOT_CONVERSATION_MAPPING = 'COPILOT_CONVERSATION_MAPPING',
  ATHAN_USER_CRM_DATA = 'ATHAN_USER_CRM_DATA',
  ATHAN_AUTH_CRM_DATA = 'ATHAN_AUTH_CRM_DATA',
  ATHAN_DIALER_LOCATION = 'ATHAN_DIALER_LOCATION',
  ATHAN_USER_CRM_TOKEN = 'ATHAN_USER_CRM_TOKEN',
  ATHAN_TENANT_CRM_DATA = 'ATHAN_TENANT_CRM_DATA',
  ATHAN_TENANT_DIALER_DATA = 'ATHAN_TENANT_DIALER_DATA',
  ACTIVITY_PANEL = 'ACTIVITY_PANEL',
  FLEX_SDK_CACHE_FEATURES_CONFIG = 'FLEX_SDK_CACHE_FEATURES_CONFIG'
} 